
# Check for an interactive session
[ -z "$PS1" ] && return

export EDITOR="vim"
PS1='\[\e[0;31m\]\u@\h\[\e[m\] \[\e[1;32m\]\w\[\e[m\] \[\e[0;31m\]\$ \[\e[m\]\[\e[1;32m\] '

# Enable history appending instead of overwriting.  #139609
shopt -s histappend

. ~/.bashrc_aliases
